### ISSUE TITLE
Model Weight error

### ISSUE THREAD

**Issue by AquaMCU** [AbdullahMakhdoom/dog_bark_detect#1]
Hi. 

Nice idea of a project. When I run the docker command, I get the following error:

/usr/local/lib/python3.10/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/app/real_time_inference.py", line 59, in <module>
    Audiocls = Audio_Classification(model_path)
  File "/app/real_time_inference.py", line 28, in __init__
    ckpt = torch.load(model_path, map_location="cpu")
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'model-weights.ckpt'

**Comment by AbdullahMakhdoom** [comment]
Link to google drive is now mentioned in the ReadMe. 
Thanks @AquaMCU.
